aws_region   = "us-east-1"
id_user_pools = "us-east-1_bBzFCrgvK"
client_id = "4qjoqslknjhd80ekclf2iecila"
function_name = "lambda-auth"
handler = "lambda-auth.lambda_handler" # O nome do arquivo e da função de manipulador
runtime = "python3.8"                 
memory_size = 128 # Tamanho da memória em MB
timeout = 5 # Tempo limite da função em segundos
id_conta = "231670762225"