aws_region   = "us-east-1"
id_user_pools = "us-east-1_v8GEEKleP"
client_id = "213abdee70ectia5lukf0hbtpd"
function_name = "lambda-authorizer"
handler = "lambda-authorizer.lambda_handler" # O nome do arquivo e da função de manipulador
runtime = "python3.8"                 
memory_size = 128 # Tamanho da memória em MB
timeout = 5 # Tempo limite da função em segundos
id_conta = "231670762225"
secret_key_jwt = "secret-jwt"